environment = "stage-ndz"
region = "eu-west-1"
ssm_param_name         = "/idlms/shared/stage-ndz/.env"
ssm_param_description  = "Shared environment variables for IDLMS in stage"
ssm_param_app_tag      = "idlms"
app_env_content         = ""
