version: "3.8"

services:
  app:
    image:  084828592148.dkr.ecr.us-east-1.amazonaws.com/license-api-dev:${BUILD_TAG}
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    working_dir: /app
    command: node dist/main.js

volumes:
  pgdata:
