services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ../src/.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ../src/.env
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    command: node dist/src/main.js
    ports:
      - "4000:4000"

volumes:
  pgdata:
