name: Deploy  Lambdaa

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment to deploy (dev/staging/prod)'
        required: true
        default: 'dev'

jobs:
  deploy-license-api:
    if: github.ref == 'refs/heads/feature/btl-52'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      ENV: ${{ github.event.inputs.ENV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./src
        run: npm ci

      - name: Build NestJS app
        working-directory: ./src
        run: npm run build

      - name: Package Lambda as ZIP
        working-directory: ./src
        run: |
          npm prune --production
          zip -r ../infra/lambda/backend-api.zip dist node_modules package.json -x "**/*.map" "**/*.d.ts" "**/test/**"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Lambda Init & Apply
        working-directory: ./infra/lambda
        run: |
          terraform init
          terraform apply -auto-approve -var-file=${{ env.ENV }}.tfvars

      - name: Terraform REST API Init & Apply
        working-directory: ./infra/api
        run: |
          terraform init
          terraform apply -auto-approve -var-file=${{ env.ENV }}.tfvars
